# Generated by Django 2.2.6 on 2024-08-27 16:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_list', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Components_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('standard_inventory_to_maintain', models.PositiveIntegerField()),
                ('inventory_category', models.CharField(choices=[('raw_material', 'raw_material'), ('semi_finished_product', 'semi_finished_product'), ('finished_product', 'finished_product')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('in_out', models.CharField(choices=[('inward', 'inward'), ('outward', 'outward')], max_length=10)),
                ('comment', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('inventory_category', models.CharField(choices=[('raw_material', 'raw_material'), ('semi_finished_product', 'semi_finished_product'), ('finished_product', 'finished_product')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
