# Generated by Django 2.2.6 on 2024-08-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_list',
            old_name='Category_list',
            new_name='Categories',
        ),
    ]
